// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAenLMNKIcQko1v16xDMWYiSiEMEZEgChg',
    appId: '1:439927785677:web:be44a9d9a99942b643c184',
    messagingSenderId: '439927785677',
    projectId: 'rentora-184ff',
    authDomain: 'rentora-184ff.firebaseapp.com',
    storageBucket: 'rentora-184ff.firebasestorage.app',
    measurementId: 'G-GLR9JT6E3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjWjOeuzwuY944BLvsnqDRGfLmic0uHiQ',
    appId: '1:439927785677:android:e5e3789693b6e5e643c184',
    messagingSenderId: '439927785677',
    projectId: 'rentora-184ff',
    storageBucket: 'rentora-184ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBknSODpnEEHcrqNZpSwm4vlzQLZqfgjwo',
    appId: '1:439927785677:ios:f16187ad881cce3443c184',
    messagingSenderId: '439927785677',
    projectId: 'rentora-184ff',
    storageBucket: 'rentora-184ff.firebasestorage.app',
    iosBundleId: 'com.example.rentora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBknSODpnEEHcrqNZpSwm4vlzQLZqfgjwo',
    appId: '1:439927785677:ios:f16187ad881cce3443c184',
    messagingSenderId: '439927785677',
    projectId: 'rentora-184ff',
    storageBucket: 'rentora-184ff.firebasestorage.app',
    iosBundleId: 'com.example.rentora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAenLMNKIcQko1v16xDMWYiSiEMEZEgChg',
    appId: '1:439927785677:web:d6cfbc6b64923ba443c184',
    messagingSenderId: '439927785677',
    projectId: 'rentora-184ff',
    authDomain: 'rentora-184ff.firebaseapp.com',
    storageBucket: 'rentora-184ff.firebasestorage.app',
    measurementId: 'G-CEKM1XR3SH',
  );
}
